%% L1 Misc Internal
graph TD
    subgraph Misc
        subgraph Misc
            Component::GameRootApp["GameRootApp"]
            Component::ProjectToolkitBootstrap["ProjectToolkitBootstrap"]
        end
    end
