%% L2 Misc External Calls
graph TD
    Feature::Misc["Misc"]
    Feature::Darkness["Darkness"]
    Feature::Misc --> Feature::Darkness
    Feature::DeathRespawn["DeathRespawn"]
    Feature::Misc --> Feature::DeathRespawn
    Feature::KeroseneLamp["KeroseneLamp"]
    Feature::Misc --> Feature::KeroseneLamp
    Feature::LightVitality["LightVitality"]
    Feature::Misc --> Feature::LightVitality
    Feature::PlayerCharacter2D["PlayerCharacter2D"]
    Feature::Misc --> Feature::PlayerCharacter2D
    Feature::RunFailReset["RunFailReset"]
    Feature::Misc --> Feature::RunFailReset
    Feature::SafeZone["SafeZone"]
    Feature::Misc --> Feature::SafeZone
