%% L1 _Shared Internal
graph TD
    subgraph _Shared
        subgraph Events
            Event::DarknessStateChangedEvent["DarknessStateChangedEvent"]
            Event::DeathCountChangedEvent["DeathCountChangedEvent"]
            Event::LampCountChangedEvent["LampCountChangedEvent"]
            Event::LampSpawnedEvent["LampSpawnedEvent"]
            Event::LightChangedEvent["LightChangedEvent"]
            Event::LightConsumedEvent["LightConsumedEvent"]
            Event::LightDepletedEvent["LightDepletedEvent"]
            Event::PlayerDiedEvent["PlayerDiedEvent"]
            Event::PlayerRespawnedEvent["PlayerRespawnedEvent"]
            Event::RunFailedEvent["RunFailedEvent"]
            Event::RunResetEvent["RunResetEvent"]
            Event::SafeZoneStateChangedEvent["SafeZoneStateChangedEvent"]
        end
        subgraph Misc
            Component::EDeathReason["EDeathReason"]
            Component::ELightConsumeReason["ELightConsumeReason"]
        end
    end
