%% L1 RunFailReset Internal
graph TD
    subgraph RunFailReset
        subgraph Controllers
            Controller::RunFailSettingsController["RunFailSettingsController"]
            Controller::RunResetController["RunResetController"]
        end
        subgraph Systems
            System::IRunFailResetSystem["IRunFailResetSystem"]
            System::RunFailResetSystem["RunFailResetSystem"]
        end
        subgraph Models
            Model::IRunFailResetModel["IRunFailResetModel"]
            Model::RunFailResetModel["RunFailResetModel"]
        end
        subgraph Commands
            Command::MarkRunFailedCommand["MarkRunFailedCommand"]
            Command::ResetRunCommand["ResetRunCommand"]
            Command::SetMaxDeathsCommand["SetMaxDeathsCommand"]
        end
    end
