%% L1 LightVitality Internal
graph TD
    subgraph LightVitality
        subgraph Controllers
            Controller::LightVitalityDebugController["LightVitalityDebugController"]
            Controller::LightVitalityResetController["LightVitalityResetController"]
        end
        subgraph Systems
            System::ILightVitalityResetSystem["ILightVitalityResetSystem"]
            System::LightVitalityResetSystem["LightVitalityResetSystem"]
        end
        subgraph Models
            Model::ILightVitalityModel["ILightVitalityModel"]
            Model::LightVitalityModel["LightVitalityModel"]
        end
        subgraph Commands
            Command::AddLightCommand["AddLightCommand"]
            Command::ConsumeLightCommand["ConsumeLightCommand"]
            Command::LightVitalityCommandUtils["LightVitalityCommandUtils"]
            Command::SetLightCommand["SetLightCommand"]
            Command::SetMaxLightCommand["SetMaxLightCommand"]
        end
        subgraph Queries
            Query::GetCurrentLightQuery["GetCurrentLightQuery"]
            Query::GetLightPercentQuery["GetLightPercentQuery"]
            Query::GetMaxLightQuery["GetMaxLightQuery"]
        end
    end
