%% L2 RunFailHandling External Calls
graph TD
    Feature::RunFailHandling["RunFailHandling"]
    Feature::RunFailReset["RunFailReset"]
    Feature::RunFailHandling --> Feature::RunFailReset
    Feature::Shared["Shared"]
    Feature::RunFailHandling --> Feature::Shared
