%% L1 PlayerCharacter2D Internal
graph TD
    subgraph PlayerCharacter2D
        subgraph Controllers
            Controller::PlatformerCharacterController["PlatformerCharacterController"]
            Controller::PlatformerCharacterInput["PlatformerCharacterInput"]
        end
        subgraph Systems
            System::PlayerCharacter2DSystem["PlayerCharacter2DSystem"]
        end
        subgraph Models
            Model::IPlayerCharacter2DModel["IPlayerCharacter2DModel"]
            Model::PlatformerFrameInput["PlatformerFrameInput"]
            Model::PlayerCharacter2DModel["PlayerCharacter2DModel"]
        end
        subgraph Commands
            Command::SetFrameInputCommand["SetFrameInputCommand"]
            Command::TickFixedStepCommand["TickFixedStepCommand"]
        end
        subgraph Queries
            Query::GetDesiredVelocityQuery["GetDesiredVelocityQuery"]
        end
        subgraph Events
            Event::PlayerGroundedChangedEvent["PlayerGroundedChangedEvent"]
            Event::PlayerJumpedEvent["PlayerJumpedEvent"]
        end
        subgraph Misc
            Component::PlatformerCharacterStats["PlatformerCharacterStats"]
        end
    end
