%% L1 SafeZone Internal
graph TD
    subgraph SafeZone
        subgraph Controllers
            Controller::PlayerSafeZoneSensor["PlayerSafeZoneSensor"]
            Controller::SafeZone2D["SafeZone2D"]
            Controller::SafeZoneTickController["SafeZoneTickController"]
        end
        subgraph Systems
            System::ISafeZoneSystem["ISafeZoneSystem"]
            System::SafeZoneSystem["SafeZoneSystem"]
        end
        subgraph Models
            Model::ISafeZoneModel["ISafeZoneModel"]
            Model::SafeZoneModel["SafeZoneModel"]
        end
        subgraph Commands
            Command::SetSafeZoneCountCommand["SetSafeZoneCountCommand"]
        end
    end
