%% L2 SafeZone External Calls
graph TD
    Feature::SafeZone["SafeZone"]
    Feature::LightVitality["LightVitality"]
    Feature::SafeZone --> Feature::LightVitality
    Feature::Shared["Shared"]
    Feature::SafeZone --> Feature::Shared
