%% L0 Features Overview
graph TD
    Feature::Darkness["Darkness"]
    Feature::DeathRespawn["DeathRespawn"]
    Feature::HUD["HUD"]
    Feature::KeroseneLamp["KeroseneLamp"]
    Feature::LightVitality["LightVitality"]
    Feature::Mechanisms["Mechanisms"]
    Feature::Misc["Misc"]
    Feature::PlayerCharacter2D["PlayerCharacter2D"]
    Feature::RunFailHandling["RunFailHandling"]
    Feature::RunFailReset["RunFailReset"]
    Feature::SafeZone["SafeZone"]
    Feature::Shared["Shared"]
    Feature::Darkness --> Feature::LightVitality
    Feature::Darkness --> Feature::Shared
    Feature::DeathRespawn --> Feature::Shared
    Feature::HUD --> Feature::Darkness
    Feature::HUD --> Feature::KeroseneLamp
    Feature::HUD --> Feature::LightVitality
    Feature::HUD --> Feature::RunFailReset
    Feature::HUD --> Feature::SafeZone
    Feature::KeroseneLamp --> Feature::Shared
    Feature::LightVitality --> Feature::Shared
    Feature::Mechanisms --> Feature::DeathRespawn
    Feature::Mechanisms --> Feature::LightVitality
    Feature::Mechanisms --> Feature::Shared
    Feature::Misc --> Feature::Darkness
    Feature::Misc --> Feature::DeathRespawn
    Feature::Misc --> Feature::KeroseneLamp
    Feature::Misc --> Feature::LightVitality
    Feature::Misc --> Feature::PlayerCharacter2D
    Feature::Misc --> Feature::RunFailReset
    Feature::Misc --> Feature::SafeZone
    Feature::PlayerCharacter2D --> Feature::Shared
    Feature::RunFailHandling --> Feature::RunFailReset
    Feature::RunFailHandling --> Feature::Shared
    Feature::RunFailReset --> Feature::Shared
    Feature::SafeZone --> Feature::LightVitality
    Feature::SafeZone --> Feature::Shared
