%% L1 Mechanisms Internal
graph TD
    subgraph Mechanisms
        subgraph Controllers
            Controller::GhostMechanism2D["GhostMechanism2D"]
            Controller::MechanismControllerBase["MechanismControllerBase"]
            Controller::SpikeHazard2D["SpikeHazard2D"]
            Controller::VineMechanism2D["VineMechanism2D"]
        end
    end
