%% L2 Mechanisms External Calls
graph TD
    Feature::Mechanisms["Mechanisms"]
    Feature::DeathRespawn["DeathRespawn"]
    Feature::Mechanisms --> Feature::DeathRespawn
    Feature::LightVitality["LightVitality"]
    Feature::Mechanisms --> Feature::LightVitality
    Feature::Shared["Shared"]
    Feature::Mechanisms --> Feature::Shared
